# fly.toml app configuration file generated for kicksdude-shopify-webhooks on 2023-06-24T19:30:26Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "kicksdude-shopify-webhooks"
primary_region = "lhr"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
